services:
  ticketsforall_backend:
    image: ticketsforall_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - ticketsforall_database
    env_file:
      - .env
    environment:
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET} 
      OAUTH_REDIRECT_URI: ${OAUTH_REDIRECT_URI}
      SQL_URL: "postgresql://root:root@ticketsforall_database:5432/ticketsforall"

    networks:
      - ticketsforall
  
  ticketsforall_database:
    container_name: ticketsforall_database
    image: postgres:latest
    environment:
      POSTGRES_DB: ticketsforall
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - ticketsforall

networks:
  ticketsforall:

volumes:
  localstack-data: