name: Docker Health Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker compose build

    - name: Run Docker container
      run: |
        docker compose up -d

    - name: Wait for container to be healthy
      run: |
        sleep 10

    - name: Check health endpoint
      run: |
        http_status=$(curl -s -o /dev/null -w "%{http_code}" 127.0.0.1:8000/health_check/)
        if [ "$http_status" -ne 200 ]; then
          echo "Health check failed with status code $http_status"
          exit 1
        fi
        echo "Health check passed with status code $http_status"
